networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    -ports:
      - "80:80"
#       - "443:443"
    volumes:
      - './nginx.conf:etc/nginx/nginx.conf'
    depends_on:
      - backend
      - fronted
    networks:
      - dev

  backend:
    build:
      context: ./backend
    networks:
      - dev


  fronted:
    build:
      context: ./fronted
    networks:
      - dev
